export { default as Header } from './Header';
export { default as Home } from './Home';
export { default as About } from './About';
export { default as PersonalSkills } from './PersonalSkills';
export { default as Process } from './Process';
export { default as Projects } from './Projects';
export { default as WorkProcess } from './WorkProcess';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';